export { Header, Navbar } from './Header'
export { Hero } from './Hero'
export { StarryBackground } from './Background'
export { About } from './About'
export { Projects, ProjectCard } from './Projects'
export { Skills } from './Skills'
export { Contact } from './Contact'
export { Footer } from './Footer'
export { default as AiChat } from './AiChat/aiChat.jsx'
